import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "hogehoge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      {/* フレックス、縦方向、画面いっぱい */}
      <body className={`${inter.className} flex flex-col h-screen bg-gray-200`}>
        <Header />
        {/* 画面目一杯に伸ばす */}
        <main className="flex-grow">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
